<?php
$scriptlang['jjsan'] = [

    'wel_back' => '欢迎回来！：）',
    'uid' => '用户id',
    'install_nickname' => '昵称',
    'submit' => '提交',
    'status' => '状态',
    'server_internal_error' => '服务器内部异常,请稍后重试',
    'price_unit' => '元',
    'borrow_record' => '租借记录',
    'no_borrow' => '暂无可借',
    'add_rule' => '添加新规则',

    'station_title' => '名称',
    'station_search' => '查询',
    'address' => '地址',

    'shop_station'            => '商铺站点',
    'shop_station_mgr'        => '商铺站点管理',
    'shop_station_station_id' => '绑定的机器id',
    'shop_station_seller_id'  => '代理',
    'shop_station_status'     => '商铺站点启用状态',
    'shop_station_remove'     => '撤机',
    'shop_station_replace'    => '换机',

    'wx_platform' => '微信',
    'alipay_platform' => '支付宝',
    'zhima_platform' => '芝麻信用',

    'order_mgr' => '订单管理',
	'order_id' => '订单号',
	'order_failed' => '下单失败，请联系客服！',
	'order_add_to_cart_succeed' => '成功添加到购物车',
	'order_add_to_cart_failed' => '添加失败，请联系客服',
	'order_cancel' => '取消订单',
	'order_cancel_succeed' => '订单取消成功',
	'order_cancel_msg' => '订单：{orderid} 已被取消',
	'order_cancel_msg_fail' => '订单：{orderid} 取消失败,请联系系统管理员',
	'order_nav_title' => '我的订单',
	'order_list' => '订单列表',
	'order_status' => '订单状态',
	'order_status_-1' => '已取消',
	'order_status_0' => '待支付',
	'order_status_1' => '已支付',
	'order_status_2' => '已派送',
	'order_status_3' => '已收货',
	'order_status_4' => '已返利',
	'order_pay' => '支付方式',
	'order_buyer' => '购买者ID',
	'order_detail' => '订单详情',
	'no_order_tip' => '暂时没有您的记录,欢迎尝试,谢谢!',
	'order_buyer_nickname' => '购买者昵称',
	'order_platform' => '订单来源',
	'order_price' => '订单价格',

    'operation'           => '操作',
    'full_return_deposit' => '全额退押金',
    'part_return_deposit' => '退部分押金',
    'money_return_deposit' => '手动退押金',
    'zhima_refund'        => '芝麻订单退款',
    'return_time'         => '归还时间',
    'return_station'      => '归还充电站',
    'calculate_other_fee' => '其他费用计入',
    'calculate'           => '计算',
    'confirm'             => '确认',
    'full_return_alert'   => '你确定要退还这个订单所有押金给用户吗？',
    'hour_period'         => '小时之内',
    'input_return_deposit'          => '请输入金额',
    'part_return_over_price'        => '根据时间计算的退款金额大于订单金额，不可退。',
    'part_return_status_not_borrow' => '订单状态非借出状态，无法部分退押金。',
    'full_return_status_not_borrow' => '订单状态非借出状态，无法全额退押金。',
    'full_return_status_duplicate'  => '无法在退过押金的状态下进行全额退押金，请在手动退押金中进行此操作。',
    'deposit_not_enough'            => '押金不足，无法退款。',
    'return_deposit_success'        => '退押金成功',

    'upload' => '上传',
    'delete' => '删除',
    'title' => '标题',
    'desc' => '描述',
    'show' => '展示',
    'close' => '关闭',
    'tags' => '标签',
    'etc' => '等等',
    'pass' => '通过',
    'all' => '全部',
    'waptitle' => '移动版',
    'pctitle' => '桌面版',
    'add_mat' => '添加素材',
    'amount_buy' => '购买数量',
    'buy_now' => '立即借出',
    'pay_now' => '立即支付',
    'add_to_cart' => '添加到购物车',
    'upload_more' => '继续上传',
    'select_all' => '全选',
    'input_desc' => '请输入描述信息',
    'input_url' => '请输入目的网址',
    'input_title' => '请输入标题',
    'input_tags' => '请输入分类标签，每种商品最多分配 5 个标签，使用空格分隔',
    'input_item_name' => '请输入商品名称',
    'input_item_desc' => '请输入商品描述信息',
    'input_amount' => '请输入待售商品数量',
    'input_price' => '请输入商品现价',
    'input_costprice' => '请输入商品原价',
    'input_flavor' => '请输入商品颜色属性，多种颜色使用空格分隔',
    'approval' => '批准',
    'notapproval' => '拒绝',
    'attachment_size' => '文件尺寸',
    'attachment_allow_exts' => '可用扩展名',
    'lower_than' => '小于',
    'size_no_limit' => '大小不限制',
    'request_processed' => '处理完毕，感谢您的使用。',
    'fatal_error' => '致命错误：{errorno}。请联系系统管理员！',
    'unit_price' => '单价',
    'amount' => '数量',
    'subtotal' => '小计',
    'total' => '总计',
    'need_login' => '需要登录',
    'only_for_mobile' => '请使用手机访问，谢谢：）',
    'illegal_operation' => '非法操作！您的行为已被记录在案！',
    'thank_for_share' => '为感谢您无私的分享行为，本次付款已享受折上折！新的价格是：',
    'lastupdate' => '最后更新时间',

    'shop_station_go_up' => '上机',
    'item_list' => '商品列表',
    'usablemoney'    => '账户余额',
    'deposit'        => '押金',
    'refund_request' => '申请提现',

    'user_detail' => '用户详情',
    'headimg'     => '用户头像',
    'user_platform'   => '用户平台',

    'settings' => '全局设置',
    'global_settings' => '全局设置',
    'system_settings' => '系统设置',
    'station_settings_strategy' => '配置同步策略',
    'credit_settings' => '积分设置',
    'fee_settings' => '收费设置',
    'develop_tools' => '开发工具',
    'wechat_settings' => '微信配置',
    'wechat_alipay_settings' => '微信/支付宝配置',
    'settings_update_success' => '配置更新成功',
    'settings_update_fail' => '配置更新失败',

];

$templatelang['jjsan'] = $scriptlang['jjsan'];
